package builtin

import (
	"strings"
	"time"

	"github.com/kkkdddd-start/winalog-go/internal/rules"
	"github.com/kkkdddd-start/winalog-go/internal/types"
)

type RuleDetail struct {
	Explanation    string
	Recommendation string
	RealCase       string
	RuleID         string
}

func GetAlertRules() []*rules.AlertRule {
	return []*rules.AlertRule{
		{
			Name:        "failed-login-threshold",
			Description: "失败登录次数超过阈值",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       70,
			MitreAttack: "T1110",
			Filter: &rules.Filter{
				EventIDs: []int32{4625},
				Levels:   []int{2},
			},
			Message: "Failed login threshold exceeded: {{.Count}} failed attempts",
			Tags:    []string{"authentication", "brute-force"},
		},
		{
			Name:        "admin-login-unusual",
			Description: "管理员账户异常登录",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1078.004",
			Filter: &rules.Filter{
				EventIDs: []int32{4624},
				Levels:   []int{4},
			},
			Message: "Unusual admin login detected for {{.User}} on {{.Computer}}",
			Tags:    []string{"authentication", "privilege"},
		},
		{
			Name:        "powershell-encoding",
			Description: "PowerShell编码命令执行",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       85,
			MitreAttack: "T1059.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4104},
				Levels:   []int{4},
			},
			Message: "Encoded PowerShell command detected",
			Tags:    []string{"powershell", "defense-evasion"},
		},
		{
			Name:        "security-log-cleared",
			Description: "安全日志被清除",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1070.001",
			Filter: &rules.Filter{
				EventIDs: []int32{1102},
				Levels:   []int{4},
			},
			Message: "Security log was cleared - potential attacker activity",
			Tags:    []string{"defense-evasion", "clearing-logs"},
		},
		{
			Name:        "account-lockout-alert",
			Description: "账户被锁定",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       50,
			MitreAttack: "T1078",
			Filter: &rules.Filter{
				EventIDs: []int32{4740},
				Levels:   []int{4},
			},
			Message: "Account {{.User}} was locked out on {{.Computer}}",
			Tags:    []string{"authentication", "account-management"},
		},
		{
			Name:        "network-connection-alert",
			Description: "可疑网络连接",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       60,
			MitreAttack: "T1059",
			Filter: &rules.Filter{
				EventIDs: []int32{3},
				Levels:   []int{4},
			},
			Message: "Suspicious network connection to port {{.DestinationPort}}",
			Tags:    []string{"network", "command-and-control"},
		},
		{
			Name:        "service-creation-alert",
			Description: "可疑服务创建",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1569.002",
			Filter: &rules.Filter{
				EventIDs: []int32{4697},
				Levels:   []int{4},
			},
			Message: "Suspicious service created: {{.ServiceName}}",
			Tags:    []string{"persistence", "service"},
		},
		{
			Name:        "scheduled-task-creation",
			Description: "可疑计划任务创建",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1053.005",
			Filter: &rules.Filter{
				EventIDs: []int32{4698},
				Levels:   []int{4},
			},
			Message: "Suspicious scheduled task created: {{.TaskName}}",
			Tags:    []string{"persistence", "scheduled-task"},
		},
		{
			Name:        "usb-device-insertion",
			Description: "USB设备接入",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       50,
			MitreAttack: "T1091",
			Filter: &rules.Filter{
				EventIDs: []int32{4663},
				Levels:   []int{4},
			},
			Message: "USB device write detected on {{.Computer}}",
			Tags:    []string{"initial-access", "physical"},
		},
		{
			Name:        "pass-the-hash-suspect",
			Description: "Pass-the-Hash 可疑特征",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       85,
			MitreAttack: "T1550.002",
			Filter: &rules.Filter{
				EventIDs: []int32{4624, 4672},
				Levels:   []int{4},
			},
			Message: "Possible Pass-the-Hash attack detected for {{.User}}",
			Tags:    []string{"credential-access", "lateral-movement"},
		},
		{
			Name:        "mimikatz-suspect",
			Description: "Mimikatz 相关工具执行",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1003",
			Filter: &rules.Filter{
				EventIDs: []int32{1},
				Levels:   []int{4},
			},
			Message: "Mimikatz or credential dumping tool detected",
			Tags:    []string{"credential-access", "malware"},
		},
		{
			Name:        "encoded-powershell-alert",
			Description: "PowerShell 远程编码命令",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       85,
			MitreAttack: "T1059.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4104},
				Levels:   []int{4},
			},
			Message: "Encoded PowerShell remote command detected",
			Tags:    []string{"powershell", "execution"},
		},
		{
			Name:        "remote-tasking-creation",
			Description: "远程任务创建 (SchTasks)",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       60,
			MitreAttack: "T1053.005",
			Filter: &rules.Filter{
				EventIDs: []int32{4698},
				Levels:   []int{4},
			},
			Message: "Remote scheduled task creation detected",
			Tags:    []string{"persistence", "remote-execution"},
		},
		{
			Name:        "suspicious-run-key",
			Description: "可疑注册表Run键自启动",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1547.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4657},
				Levels:   []int{4},
			},
			Message: "Suspicious Run key modification detected",
			Tags:    []string{"persistence", "registry"},
		},
		{
			Name:        "suspicious-dll-load",
			Description: "可疑DLL加载",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       60,
			MitreAttack: "T1574.001",
			Filter: &rules.Filter{
				EventIDs: []int32{7},
				Levels:   []int{4},
			},
			Message: "Suspicious DLL loaded from unusual location",
			Tags:    []string{"defense-evasion", "persistence"},
		},
		{
			Name:        "wmi-suspicious",
			Description: "可疑WMI活动",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       65,
			MitreAttack: "T1047",
			Filter: &rules.Filter{
				EventIDs: []int32{5861},
				Levels:   []int{4},
			},
			Message: "Suspicious WMI activity detected",
			Tags:    []string{"persistence", "execution"},
		},
		{
			Name:        "registry-run-key-modification",
			Description: "注册表Run键自启动项被修改",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1547.001",
			Filter: &rules.Filter{
				EventIDs: []int32{13},
				Levels:   []int{4},
			},
			Message: "Registry Run key modified: {{.TargetObject}}",
			Tags:    []string{"persistence", "registry"},
		},
		{
			Name:        "registry-services-modification",
			Description: "注册表服务启动类型被修改",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1543.003",
			Filter: &rules.Filter{
				EventIDs: []int32{13},
				Levels:   []int{4},
			},
			Message: "Service registry modified: {{.TargetObject}}",
			Tags:    []string{"persistence", "registry"},
		},
		{
			Name:        "registry-hive-modification",
			Description: "注册表Hive被修改(安全相关)",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       95,
			MitreAttack: "T1003.002",
			Filter: &rules.Filter{
				EventIDs: []int32{13},
				Levels:   []int{4},
			},
			Message: "Critical registry hive modification: {{.TargetObject}}",
			Tags:    []string{"credential-access", "registry"},
		},
		{
			Name:        "registry-wmi-persistence",
			Description: "WMI注册表持久化修改",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1546.003",
			Filter: &rules.Filter{
				EventIDs: []int32{13},
				Levels:   []int{4},
			},
			Message: "WMI registry persistence modification detected",
			Tags:    []string{"persistence", "wmi"},
		},
		{
			Name:        "registry-bypass-detection",
			Description: "注册表绕过技术(AlwaysInstallElevated)",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1548.001",
			Filter: &rules.Filter{
				EventIDs: []int32{13},
				Levels:   []int{4},
			},
			Message: "UAC bypass technique via registry detected",
			Tags:    []string{"privilege-escalation", "defense-evasion"},
		},
		{
			Name:        "wmic-suspicious",
			Description: "可疑WMIC命令执行",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1047",
			Filter: &rules.Filter{
				EventIDs: []int32{4688},
				Levels:   []int{4},
			},
			Message: "Suspicious WMIC command executed",
			Tags:    []string{"execution", "wmi"},
		},
		{
			Name:        "winrm-suspicious",
			Description: "可疑WinRM远程命令",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1028",
			Filter: &rules.Filter{
				EventIDs: []int32{4688},
				Levels:   []int{4},
			},
			Message: "Suspicious WinRM activity detected",
			Tags:    []string{"lateral-movement", "remote-execution"},
		},
		{
			Name:        "winrm-remote-connection",
			Description: "WinRM远程连接",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       55,
			MitreAttack: "T1028",
			Filter: &rules.Filter{
				EventIDs: []int32{6},
				Levels:   []int{4},
			},
			Message: "WinRM remote connection established",
			Tags:    []string{"lateral-movement", "remote-execution"},
		},
		{
			Name:        "domain-recon",
			Description: "域内侦察活动",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       70,
			MitreAttack: "T1018",
			Filter: &rules.Filter{
				EventIDs: []int32{4688},
				Levels:   []int{4},
			},
			Message: "Domain reconnaissance activity detected",
			Tags:    []string{"discovery", "active-directory"},
		},
		{
			Name:        "domain-admin-login",
			Description: "域管理员登录检测",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       95,
			MitreAttack: "T1078.002",
			Filter: &rules.Filter{
				EventIDs: []int32{4624},
				Levels:   []int{4},
			},
			Message: "Domain administrator login detected from {{.IpAddress}}",
			Tags:    []string{"privilege-access", "lateral-movement"},
		},
		{
			Name:        "dc-sync-attack",
			Description: "DCSync攻击特征检测",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1003.004",
			Filter: &rules.Filter{
				EventIDs: []int32{4624, 4672},
				Levels:   []int{4},
			},
			Message: "Possible DCSync attack detected - domain replication",
			Tags:    []string{"credential-access", "lateral-movement"},
		},
		{
			Name:        "kerberoasting",
			Description: "Kerberoasting攻击检测",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       85,
			MitreAttack: "T1558.003",
			Filter: &rules.Filter{
				EventIDs: []int32{4769},
				Levels:   []int{4},
			},
			Message: "Kerberoasting attack pattern detected - TGS request for {{.TargetUserName}}",
			Tags:    []string{"credential-access", "kerberos"},
		},
		{
			Name:        "golden-ticket",
			Description: "黄金票据特征检测",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1558.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4624},
				Levels:   []int{4},
			},
			Message: "Golden ticket attack特征 detected - krbtgt login from unusual source",
			Tags:    []string{"credential-access", "persistence"},
		},
		{
			Name:        "powershell-remoting",
			Description: "PowerShell远程执行",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1028.003",
			Filter: &rules.Filter{
				EventIDs: []int32{4688},
				Levels:   []int{4},
			},
			Message: "PowerShell remoting session detected",
			Tags:    []string{"lateral-movement", "powershell"},
		},
		{
			Name:        "powershell-download",
			Description: "PowerShell恶意下载",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       95,
			MitreAttack: "T1105",
			Filter: &rules.Filter{
				EventIDs: []int32{4104},
				Levels:   []int{4},
			},
			Message: "Malicious PowerShell download detected",
			Tags:    []string{"command-and-control", "powershell"},
		},
		{
			Name:        "certutil-download",
			Description: "CertUtil恶意下载",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       90,
			MitreAttack: "T1105",
			Filter: &rules.Filter{
				EventIDs: []int32{4688},
				Levels:   []int{4},
			},
			Message: "CertUtil used for malicious download detected",
			Tags:    []string{"command-and-control", "defense-evasion"},
		},
		{
			Name:        "smb-lateral-movement",
			Description: "SMB横向移动检测",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1021.002",
			Filter: &rules.Filter{
				EventIDs: []int32{5145, 5140},
				Levels:   []int{4},
			},
			Message: "SMB lateral movement detected to {{.Computer}}",
			Tags:    []string{"lateral-movement", "smb"},
		},
		{
			Name:        "smb-unauthenticated-access",
			Description: "SMB未授权访问",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1021.002",
			Filter: &rules.Filter{
				EventIDs: []int32{5140},
				Levels:   []int{4},
			},
			Message: "Unauthenticated SMB access detected",
			Tags:    []string{"lateral-movement", "smb"},
		},
		{
			Name:        "rdp-lateral-movement",
			Description: "RDP横向移动检测(外部IP)",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       90,
			MitreAttack: "T1021.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4624},
				Levels:   []int{4},
			},
			Message: "RDP lateral movement detected from external IP: {{.IpAddress}}",
			Tags:    []string{"lateral-movement", "rdp"},
		},
		{
			Name:        "rdp-brute-force",
			Description: "RDP暴力破解检测",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1110.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4625},
				Levels:   []int{2},
			},
			Message: "RDP brute force attack detected - {{.Count}} failed attempts",
			Tags:    []string{"credential-access", "brute-force"},
		},
		{
			Name:        "wmi-event-subscription",
			Description: "WMI Event Subscription持久化",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1546.003",
			Filter: &rules.Filter{
				EventIDs: []int32{5861},
				Levels:   []int{4},
			},
			Message: "WMI event subscription created - possible persistence",
			Tags:    []string{"persistence", "wmi"},
		},
		{
			Name:        "com-object-hijacking",
			Description: "COM对象劫持持久化",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       85,
			MitreAttack: "T1546.001",
			Filter: &rules.Filter{
				EventIDs: []int32{13},
				Levels:   []int{4},
			},
			Message: "COM object hijacking detected: {{.TargetObject}}",
			Tags:    []string{"persistence", "defense-evasion"},
		},
		{
			Name:        "dll-search-order-hijacking",
			Description: "DLL搜索顺序劫持持久化",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1574.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4688},
				Levels:   []int{4},
			},
			Message: "DLL search order hijacking detected",
			Tags:    []string{"persistence", "defense-evasion"},
		},
		{
			Name:        "service-dll-hijacking",
			Description: "服务DLL劫持持久化",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       95,
			MitreAttack: "T1574.002",
			Filter: &rules.Filter{
				EventIDs: []int32{4697},
				Levels:   []int{4},
			},
			Message: "Service DLL hijacking detected: {{.ServiceName}}",
			Tags:    []string{"persistence", "privilege-escalation"},
		},
		{
			Name:        "dns-tunneling",
			Description: "DNS隧道特征检测",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       90,
			MitreAttack: "T1071.004",
			Filter: &rules.Filter{
				EventIDs: []int32{4688, 3},
				Levels:   []int{4},
			},
			Message: "DNS tunneling特征 detected - possible C2 communication",
			Tags:    []string{"command-and-control", "exfiltration"},
		},
		{
			Name:        "cobalt-strike-beacon",
			Description: "Cobalt Strike Beacon特征检测",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1027.005",
			Filter: &rules.Filter{
				EventIDs: []int32{4688},
				Levels:   []int{4},
			},
			Message: "Cobalt Strike beacon特征 detected - {{.Computer}} may be compromised",
			Tags:    []string{"malware", "command-and-control"},
		},
		{
			Name:        "cobalt-strike-pipe",
			Description: "Cobalt Strike命名管道特征",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1021.002",
			Filter: &rules.Filter{
				EventIDs: []int32{17, 18},
				Levels:   []int{4},
			},
			Message: "Cobalt Strike named pipe detected",
			Tags:    []string{"malware", "command-and-control"},
		},
		{
			Name:        "suspicious-powershell-loop",
			Description: "PowerShell循环执行检测",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1059.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4104},
				Levels:   []int{4},
			},
			Message: "PowerShell loop execution detected - possible download cycle",
			Tags:    []string{"persistence", "powershell"},
		},
		{
			Name:        "powershell-no-profile",
			Description: "PowerShell无Profile执行(规避检测)",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       55,
			MitreAttack: "T1059.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4104},
				Levels:   []int{4},
			},
			Message: "PowerShell execution without profile - possible evasion",
			Tags:    []string{"defense-evasion", "powershell"},
		},
		{
			Name:        "sysmon-network-suspicious-port",
			Description: "Sysmon可疑网络连接(高位端口)",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       60,
			MitreAttack: "T1043",
			Filter: &rules.Filter{
				EventIDs: []int32{3},
				Levels:   []int{4},
			},
			Message: "Connection to suspicious port {{.DestinationPort}}",
			Tags:    []string{"command-and-control", "network"},
		},
		{
			Name:        "sysmon-network-outbound",
			Description: "Sysmon可疑出站连接",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       70,
			MitreAttack: "T1049",
			Filter: &rules.Filter{
				EventIDs: []int32{3},
				Levels:   []int{4},
			},
			Message: "Suspicious outbound connection to {{.DestinationIp}}",
			Tags:    []string{"command-and-control", "network"},
		},
		{
			Name:        "sysmon-dll-suspicious-path",
			Description: "Sysmon可疑路径DLL加载",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1574.001",
			Filter: &rules.Filter{
				EventIDs: []int32{7},
				Levels:   []int{4},
			},
			Message: "DLL loaded from suspicious path: {{.ImageLoaded}}",
			Tags:    []string{"defense-evasion", "persistence"},
		},
		{
			Name:        "sysmon-dll-lsass",
			Description: "Sysmon LSASS进程DLL加载",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1003.001",
			Filter: &rules.Filter{
				EventIDs: []int32{7},
				Levels:   []int{4},
			},
			Message: "Suspicious DLL loaded into LSASS - possible credential dumping",
			Tags:    []string{"credential-access", "malware"},
		},
		{
			Name:        "sysmon-file-suspicious-location",
			Description: "Sysmon可疑位置文件创建",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       55,
			MitreAttack: "T1547.001",
			Filter: &rules.Filter{
				EventIDs: []int32{11},
				Levels:   []int{4},
			},
			Message: "File created in suspicious location: {{.TargetFilename}}",
			Tags:    []string{"persistence", "initial-access"},
		},
		{
			Name:        "sysmon-file-executable",
			Description: "Sysmon可执行文件创建",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       70,
			MitreAttack: "T1127",
			Filter: &rules.Filter{
				EventIDs: []int32{11},
				Levels:   []int{4},
			},
			Message: "Executable file created: {{.TargetFilename}}",
			Tags:    []string{"initial-access", "malware"},
		},
		{
			Name:        "sysmon-pipe-suspicious",
			Description: "Sysmon可疑命名管道",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1021.002",
			Filter: &rules.Filter{
				EventIDs: []int32{17, 18},
				Levels:   []int{4},
			},
			Message: "Suspicious named pipe created: {{.PipeName}}",
			Tags:    []string{"lateral-movement", "command-and-control"},
		},
		{
			Name:        "ueba-off-hours-login",
			Description: "用户异常时间登录(UEBA)",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       45,
			MitreAttack: "T1078",
			Filter: &rules.Filter{
				EventIDs: []int32{4624},
				Levels:   []int{4},
			},
			Message: "Off-hours login detected for {{.User}}",
			Tags:    []string{"authentication", "anomaly-detection"},
		},
		{
			Name:        "ueba-massive-file-access",
			Description: "用户大量文件访问(UEBA)",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       50,
			MitreAttack: "T1036",
			Filter: &rules.Filter{
				EventIDs: []int32{4663},
				Levels:   []int{4},
			},
			Message: "Massive file access by {{.User}} - possible data exfiltration",
			Tags:    []string{"exfiltration", "anomaly-detection"},
		},
		{
			Name:        "ueba-privilege-escalation",
			Description: "用户权限提升行为(UEBA)",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1068",
			Filter: &rules.Filter{
				EventIDs: []int32{4672, 4673, 4674},
				Levels:   []int{4},
			},
			Message: "Privilege escalation detected for {{.User}}",
			Tags:    []string{"privilege-escalation", "anomaly-detection"},
		},
		{
			Name:        "amsi-bypass",
			Description: "AMSI绕过检测(篡改AmsiInitProvider或AmsiUtils)",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       95,
			MitreAttack: "T1562.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4104},
				Levels:   []int{4},
			},
			Message: "AMSI bypass attempt detected - attacker trying to disable antivirus",
			Tags:    []string{"defense-evasion", "anti-antivirus"},
		},
		{
			Name:        "etw-tampering",
			Description: "ETW日志干扰检测(禁用Windows事件追踪)",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       95,
			MitreAttack: "T1562.006",
			Filter: &rules.Filter{
				EventIDs: []int32{4104, 4688},
				Levels:   []int{4},
			},
			Message: "ETW tampering detected - possible defense evasion",
			Tags:    []string{"defense-evasion", "clearing-logs"},
		},
		{
			Name:        "defender-realtime-disabled",
			Description: "Defender实时保护被禁用",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       95,
			MitreAttack: "T1562.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4688, 4657},
				Levels:   []int{4},
			},
			Message: "Windows Defender real-time protection disabled",
			Tags:    []string{"defense-evasion", "malware"},
		},
		{
			Name:        "shadow-copy-deletion",
			Description: "卷影副本删除(vssadmin/wmic)",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1490",
			Filter: &rules.Filter{
				EventIDs: []int32{4688},
				Levels:   []int{4},
			},
			Message: "Volume shadow copy deleted - possible ransomware preparation",
			Tags:    []string{"impact", "ransomware"},
		},
		{
			Name:        "defender-exclusion-added",
			Description: "Defender排除路径添加",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1562.001",
			Filter: &rules.Filter{
				EventIDs: []int32{4688, 4104},
				Levels:   []int{4},
			},
			Message: "Antivirus exclusion added: {{.CommandLine}}",
			Tags:    []string{"defense-evasion", "malware"},
		},
		{
			Name:        "event-log-cleared-system",
			Description: "系统日志被清除",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       85,
			MitreAttack: "T1070.001",
			Filter: &rules.Filter{
				EventIDs: []int32{104, 1102},
				Levels:   []int{4},
			},
			Message: "System event log cleared",
			Tags:    []string{"defense-evasion", "clearing-logs"},
		},
		{
			Name:        "ntlm-v1-authentication",
			Description: "NTLMv1降级认证(易受中继攻击)",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1550.002",
			Filter: &rules.Filter{
				EventIDs: []int32{4624},
				Levels:   []int{4},
			},
			Message: "NTLMv1 authentication detected - vulnerable to relay attack",
			Tags:    []string{"credential-access", "relay-attack"},
		},
		{
			Name:        "bloodhound-detection",
			Description: "BloodHound/SharpHound AD枚举工具检测",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       85,
			MitreAttack: "T1018",
			Filter: &rules.Filter{
				EventIDs: []int32{4688, 4104},
				Levels:   []int{4},
			},
			Message: "BloodHound/SharpHound AD reconnaissance tool detected",
			Tags:    []string{"discovery", "active-directory"},
		},
		{
			Name:        "psexec-remote-execution",
			Description: "PsExec远程执行检测",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1570",
			Filter: &rules.Filter{
				EventIDs: []int32{4688, 5145},
				Levels:   []int{4},
			},
			Message: "PsExec remote execution detected",
			Tags:    []string{"lateral-movement", "remote-execution"},
		},
		{
			Name:        "certutil-download-suspect",
			Description: "Certutil下载器检测(非证书操作)",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1105",
			Filter: &rules.Filter{
				EventIDs: []int32{4688},
				Levels:   []int{4},
			},
			Message: "CertUtil used for download: {{.CommandLine}}",
			Tags:    []string{"command-and-control", "defense-evasion"},
		},
		{
			Name:        "bcdedit-modification",
			Description: "BCD启动配置修改检测",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       90,
			MitreAttack: "T1542.003",
			Filter: &rules.Filter{
				EventIDs: []int32{4688},
				Levels:   []int{4},
			},
			Message: "Boot Configuration Data modified - possible stealth technique",
			Tags:    []string{"defense-evasion", "persistence"},
		},
		{
			Name:        "lsass-memory-dump",
			Description: "LSASS内存转储检测(凭据窃取)",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1003.001",
			Filter: &rules.Filter{
				EventIDs: []int32{10},
				Levels:   []int{4},
			},
			Message: "LSASS memory dump detected - credential theft",
			Tags:    []string{"credential-access", "malware"},
		},
		{
			Name:        "dcsync-attack",
			Description: "DCSync攻击检测(非授权目录复制)",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1003.006",
			Filter: &rules.Filter{
				EventIDs: []int32{4662},
				Levels:   []int{4},
			},
			Message: "DCSync attack detected - unauthorized domain replication",
			Tags:    []string{"credential-access", "lateral-movement"},
		},
		{
			Name:        "tunneling-tool-detected",
			Description: "内网穿透工具检测(frp/ngrok/chisel等)",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       85,
			MitreAttack: "T1090.002",
			Filter: &rules.Filter{
				EventIDs: []int32{4688, 1},
				Levels:   []int{4},
			},
			Message: "Tunneling tool detected: {{.Image}}",
			Tags:    []string{"command-and-control", "exfiltration"},
		},
		{
			Name:        "cloud-storage-upload",
			Description: "云存储上传检测(数据外泄)",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       60,
			MitreAttack: "T1567.002",
			Filter: &rules.Filter{
				EventIDs: []int32{3},
				Levels:   []int{4},
			},
			Message: "Connection to cloud storage: {{.DestinationHostname}}",
			Tags:    []string{"exfiltration", "command-and-control"},
		},
		{
			Name:        "ransomware-file-encryption",
			Description: "勒索软件文件加密行为检测",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       100,
			MitreAttack: "T1486",
			Filter: &rules.Filter{
				EventIDs: []int32{11},
				Levels:   []int{4},
			},
			Message: "Ransomware file encryption pattern detected: {{.TargetFilename}}",
			Tags:    []string{"impact", "ransomware"},
		},
		{
			Name:        "startup-folder-write",
			Description: "启动文件夹写入检测(持久化)",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       55,
			MitreAttack: "T1547.001",
			Filter: &rules.Filter{
				EventIDs: []int32{11},
				Levels:   []int{4},
			},
			Message: "Executable written to startup folder",
			Tags:    []string{"persistence", "initial-access"},
		},
		{
			Name:        "registry-service-persistence",
			Description: "注册表服务键持久化检测",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1543.003",
			Filter: &rules.Filter{
				EventIDs: []int32{13},
				Levels:   []int{4},
			},
			Message: "Service registry key modified for persistence",
			Tags:    []string{"persistence", "privilege-escalation"},
		},
		{
			Name:        "winrm-brute-force",
			Description: "WinRM暴力破解检测",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1110.001",
			Filter: &rules.Filter{
				EventIDs: []int32{20, 22},
				Levels:   []int{4},
			},
			Message: "WinRM brute force attack detected",
			Tags:    []string{"credential-access", "brute-force"},
		},
		{
			Name:        "winrm-unauthorized-enable",
			Description: "WinRM服务被未授权启用",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1028",
			Filter: &rules.Filter{
				EventIDs: []int32{6},
				Levels:   []int{4},
			},
			Message: "WinRM service unauthorized enabled",
			Tags:    []string{"persistence", "lateral-movement"},
		},
		{
			Name:        "winrm-suspicious-shell",
			Description: "WinRM可疑Shell创建",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1028.003",
			Filter: &rules.Filter{
				EventIDs: []int32{91, 28, 30},
				Levels:   []int{4},
			},
			Message: "Suspicious WinRM shell created",
			Tags:    []string{"lateral-movement", "remote-execution"},
		},
		{
			Name:        "winrm-powershell-execution",
			Description: "WinRM远程PowerShell命令执行",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       90,
			MitreAttack: "T1059.001",
			Filter: &rules.Filter{
				EventIDs: []int32{33},
				Levels:   []int{4},
			},
			Message: "PowerShell executed via WinRM remote session",
			Tags:    []string{"lateral-movement", "powershell"},
		},
		{
			Name:        "winrm-remote-command",
			Description: "WinRM远程命令执行",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1028",
			Filter: &rules.Filter{
				EventIDs: []int32{32},
				Levels:   []int{4},
			},
			Message: "Remote command executed via WinRM",
			Tags:    []string{"lateral-movement", "remote-execution"},
		},
		{
			Name:        "winrm-lateral-movement",
			Description: "WinRM横向移动检测(外部IP)",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       90,
			MitreAttack: "T1028.004",
			Filter: &rules.Filter{
				EventIDs: []int32{4624},
				Levels:   []int{4},
			},
			Message: "WinRM lateral movement from external IP: {{.IpAddress}}",
			Tags:    []string{"lateral-movement", "remote-execution"},
		},
		{
			Name:        "winrm-admin-lateral",
			Description: "WinRM管理员账户横向移动",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       95,
			MitreAttack: "T1028.004",
			Filter: &rules.Filter{
				EventIDs: []int32{4624, 30},
				Levels:   []int{4},
			},
			Message: "Admin account WinRM lateral movement detected",
			Tags:    []string{"lateral-movement", "privilege-access"},
		},
		{
			Name:        "winrm-credential-theft",
			Description: "WinRM凭据窃取特征检测",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Score:       95,
			MitreAttack: "T1003.001",
			Filter: &rules.Filter{
				EventIDs: []int32{10, 30},
				Levels:   []int{4},
			},
			Message: "Credential theft特征 via WinRM: LSASS access",
			Tags:    []string{"credential-access", "malware"},
		},
		{
			Name:        "winrm-suspicious-data-transfer",
			Description: "WinRM可疑数据传输",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       55,
			MitreAttack: "T1048",
			Filter: &rules.Filter{
				EventIDs: []int32{85, 86},
				Levels:   []int{4},
			},
			Message: "Large data transfer via WinRM: {{.Size}} bytes",
			Tags:    []string{"exfiltration", "command-and-control"},
		},
		{
			Name:        "winrm-channel-creation-flood",
			Description: "WinRM Channel创建异常(可能的隧道建立)",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1028.003",
			Filter: &rules.Filter{
				EventIDs: []int32{8, 12},
				Levels:   []int{4},
			},
			Message: "Abnormal WinRM channel creation detected",
			Tags:    []string{"command-and-control", "tunneling"},
		},
		{
			Name:        "winrm-certificate-mapping-fail",
			Description: "WinRM证书映射失败(可能的攻击探测)",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       50,
			MitreAttack: "T1556",
			Filter: &rules.Filter{
				EventIDs: []int32{184, 182, 191},
				Levels:   []int{4},
			},
			Message: "WinRM certificate mapping failure - possible reconnaissance",
			Tags:    []string{"discovery", "authentication"},
		},
		{
			Name:        "winrm-plugin-loading",
			Description: "WinRM插件加载检测",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1543",
			Filter: &rules.Filter{
				EventIDs: []int32{162},
				Levels:   []int{4},
			},
			Message: "Suspicious WinRM plugin loaded: {{.PluginName}}",
			Tags:    []string{"persistence", "privilege-escalation"},
		},
		{
			Name:        "winrm-remote-forwarding",
			Description: "WinRM远程端口转发检测",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1028.004",
			Filter: &rules.Filter{
				EventIDs: []int32{169},
				Levels:   []int{4},
			},
			Message: "WinRM remote port forwarding detected",
			Tags:    []string{"lateral-movement", "tunneling"},
		},
		{
			Name:        "suspicious-privilege-use",
			Description: "可疑特权使用",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       75,
			MitreAttack: "T1098",
			Filter: &rules.Filter{
				EventIDs: []int32{4673, 4674},
				Levels:   []int{4},
			},
			Message: "Suspicious privilege use detected",
			Tags:    []string{"privilege-escalation", "persistence"},
		},
		{
			Name:        "mass-privilege-assignment",
			Description: "批量特权分配",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Score:       80,
			MitreAttack: "T1098",
			Filter: &rules.Filter{
				EventIDs: []int32{4672},
				Levels:   []int{4},
			},
			Message: "Mass privilege assignment detected - {{.Count}} events",
			Tags:    []string{"privilege-escalation", "persistence"},
		},
		{
			Name:        "key-operations-alert",
			Description: "密钥操作告警",
			Enabled:     true,
			Severity:    types.SeverityMedium,
			Score:       55,
			MitreAttack: "T1003",
			Filter: &rules.Filter{
				EventIDs: []int32{5058, 5059, 5061},
				Levels:   []int{4},
			},
			Message: "Cryptographic key operation detected",
			Tags:    []string{"credential-access", "discovery"},
		},
	}
}

func GetCorrelationRules() []*rules.CorrelationRule {
	return []*rules.CorrelationRule{
		{
			Name:        "brute-force-attack",
			Description: "暴力破解攻击模式",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Patterns: []*rules.Pattern{
				{EventID: 4625},
				{EventID: 4625},
				{EventID: 4625},
			},
			TimeWindow:  5 * time.Minute,
			Join:        "user",
			MitreAttack: "T1110",
		},
		{
			Name:        "lateral-movement",
			Description: "横向移动攻击模式",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Patterns: []*rules.Pattern{
				{EventID: 4624},
				{EventID: 4648},
			},
			TimeWindow:  1 * time.Minute,
			Join:        "user",
			MitreAttack: "T1021",
		},
		{
			Name:        "privilege-escalation-chain",
			Description: "权限提升攻击链",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Patterns: []*rules.Pattern{
				{EventID: 4672},
				{EventID: 4688},
			},
			TimeWindow:  1 * time.Minute,
			Join:        "user",
			MitreAttack: "T1548",
		},
		{
			Name:        "persistence-chain",
			Description: "持久化攻击链",
			Enabled:     true,
			Severity:    types.SeverityHigh,
			Patterns: []*rules.Pattern{
				{EventID: 4688},
				{EventID: 4698},
			},
			TimeWindow:  5 * time.Minute,
			Join:        "user",
			MitreAttack: "T1053",
		},
		{
			Name:        "credential-dump-chain",
			Description: "凭据窃取攻击链",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Patterns: []*rules.Pattern{
				{EventID: 4688, Conditions: []*rules.Condition{{Field: "NewProcessName", Operator: "contains", Value: "mimikatz"}}},
				{EventID: 10},
			},
			TimeWindow:  1 * time.Minute,
			Join:        "user",
			MitreAttack: "T1003",
		},
		{
			Name:        "ransomware-preparation",
			Description: "勒索软件准备阶段",
			Enabled:     true,
			Severity:    types.SeverityCritical,
			Patterns: []*rules.Pattern{
				{EventID: 4688, Conditions: []*rules.Condition{{Field: "CommandLine", Operator: "contains", Value: "vssadmin"}}},
				{EventID: 4688, Conditions: []*rules.Condition{{Field: "CommandLine", Operator: "contains", Value: "delete"}}},
			},
			TimeWindow:  5 * time.Minute,
			Join:        "",
			MitreAttack: "T1490",
		},
	}
}

var ruleDetails = map[string]RuleDetail{
	"failed-login-threshold": {
		RuleID:         "T1110",
		Explanation:    "检测同一账户在短时间内多次登录失败，这是暴力破解攻击的典型特征。攻击者通常使用自动化工具尝试大量密码组合来获取账户访问权限。",
		Recommendation: "1. 确认是否为合法用户忘记密码导致\n2. 封锁相关IP地址\n3. 启用账户锁定策略\n4. 强制使用强密码策略\n5. 考虑部署多因素认证(MFA)",
		RealCase:       "2020年Twitter遭遇OAuth暴力破解攻击，攻击者利用自动化工具尝试获取内部员工凭证，最终导致多个高价值账户被劫持。",
	},
	"mimikatz-suspect": {
		RuleID:         "T1003",
		Explanation:    "Mimikatz是最常用的凭据窃取工具，可从LSASS进程中提取明文密码、Kerberos票据和哈希。攻击者常在横向移动前使用此工具。",
		Recommendation: "1. 立即隔离受感染主机\n2. 检查是否有其他凭据泄露\n3. 部署Credential Guard保护凭据\n4. 启用LSASS进程保护\n5. 审查本地管理员权限分配",
		RealCase:       "2017年NotPetya勒索软件攻击中，攻击者利用Mimikatz在多个乌克兰企业网络中传播。",
	},
	"security-log-cleared": {
		RuleID:         "T1070.001",
		Explanation:    "清除安全日志是攻击者隐藏入侵痕迹的常用手法。通过删除1102事件，可以抹除账户登录、服务创建等关键安全事件记录。",
		Recommendation: "1. 确认为谁在何时执行了清除操作\n2. 检查清除前的日志是否有其他可疑活动\n3. 立即备份现有日志\n4. 部署集中日志收集方案\n5. 设置日志删除告警",
		RealCase:       "2017年Equifax数据泄露事件中，攻击者清除安全日志以隐藏其活动轨迹，导致调查人员难以确定入侵时间线。",
	},
	"kerberoasting": {
		RuleID:         "T1558.003",
		Explanation:    "Kerberoasting攻击利用Kerberos认证协议的弱点。攻击者请求服务票据后离线破解获取服务账户密码，这类账户密码通常较为简单。",
		Recommendation: "1. 确保服务账户使用强密码(25位以上)\n2. 定期轮换服务账户密码\n3. 启用AES加密强制使用\n4. 监控异常的TGS请求模式\n5. 限制服务账户的登录权限",
		RealCase:       "2022年Lapsus$组织使用Kerberoasting攻击获取多个企业包括微软、三星的初始访问权限。",
	},
	"golden-ticket": {
		RuleID:         "T1558.001",
		Explanation:    "黄金票据攻击伪造Kerberos票据授予服务(TGS)，允许攻击者冒充任意用户包括域管理员。攻击者需要获取krbtgt账户哈希。",
		Recommendation: "1. 立即重置krbtgt密码两次\n2. 检查是否使用了伪造票据\n3. 审查所有域管理员会话\n4. 启用Kerberos青铜位标志策略\n5. 部署AD安全监控",
		RealCase:       "2014年德国电信遭Golden Ticket攻击，攻击者利用伪造票据访问内部系统数月。",
	},
	"powershell-encoding": {
		RuleID:         "T1059.001",
		Explanation:    "攻击者使用Base64编码的PowerShell命令来规避检测。编码后的命令难以被传统安全设备识别，是高级持续性威胁(APT)的常用技术。",
		Recommendation: "1. 启用PowerShell脚本块日志记录\n2. 监控PowerShell执行网络连接\n3. 部署约束语言模式\n4. 使用PowerShell v5+的改进安全功能\n5. 考虑使用AppLocker限制PowerShell执行",
		RealCase:       "FIN7组织使用编码PowerShell进行针对性攻击，窃取数百万张支付卡信息。",
	},
	"shadow-copy-deletion": {
		RuleID:         "T1490",
		Explanation:    "删除卷影副本是勒索软件的典型行为，通过删除文件的备份副本使受害者无法恢复数据。攻击者通常在加密前执行此操作。",
		Recommendation: "1. 立即隔离受感染主机\n2. 检查是否有离线备份可用\n3. 通知应急响应团队\n4. 封锁勒索软件 C2通信\n5. 准备恢复方案",
		RealCase:       "2017年WannaCry攻击中，攻击者使用vssadmin delete shadows命令删除卷影副本，使受害者无法通过系统还原点恢复文件。",
	},
	"registry-run-key-modification": {
		RuleID:         "T1547.001",
		Explanation:    "修改注册表Run键是最常见的持久化技术之一。恶意软件通过添加Run键实现在系统启动时自动运行，常被APT组织使用。",
		Recommendation: "1. 检查Run键中的程序是否可信\n2. 分析程序来源和哈希\n3. 检查系统启动项的完整性\n4. 部署注册表监控\n5. 使用最小权限原则",
		RealCase:       "Emotet木马通过注册表Run键实现持久化，感染全球超过100万台设备。",
	},
	"service-creation-alert": {
		RuleID:         "T1569.002",
		Explanation:    "创建可疑服务是攻击者实现持久化和权限维持的常用方法。恶意服务可以在系统启动时以高权限运行，且难以被用户发现。",
		Recommendation: "1. 检查服务二进制文件位置和哈希\n2. 审查服务创建者的身份\n3. 检查服务是否具有异常权限\n4. 使用Autoruns等工具全面检查持久化\n5. 部署服务创建审核策略",
		RealCase:       "APT29(Cozy Bear)使用恶意Windows服务实现持久化，2016年美国民主党全国委员会入侵事件中首次被发现。",
	},
	"scheduled-task-creation": {
		RuleID:         "T1053.005",
		Explanation:    "创建计划任务是攻击者实现定时执行的常用技术。与服务持久化相比，计划任务更易于远程创建且更难被检测。",
		Recommendation: "1. 检查任务创建者权限\n2. 审查任务执行的操作\n3. 检查任务是否与已知合法软件相关\n4. 监控任务修改行为\n5. 禁用不必要的计划任务创建权限",
		RealCase:       "Wizard Spider勒索软件组织使用计划任务在特定时间执行勒索操作，选择在非工作时间最大化影响。",
	},
}

func GetRuleExplanation(ruleName string) string {
	if detail, ok := ruleDetails[ruleName]; ok {
		return detail.Explanation
	}
	return "暂无详细规则解读"
}

func GetRuleRecommendation(ruleName string) string {
	if detail, ok := ruleDetails[ruleName]; ok {
		return detail.Recommendation
	}
	return "暂无处置建议"
}

func GetRuleRealCase(ruleName string) string {
	if detail, ok := ruleDetails[ruleName]; ok {
		return detail.RealCase
	}
	return "暂无真实案例"
}

func GetRuleDetails(ruleName string) (explanation, recommendation, realCase string) {
	if detail, ok := ruleDetails[ruleName]; ok {
		return detail.Explanation, detail.Recommendation, detail.RealCase
	}
	return "暂无详细规则解读", "暂无处置建议", "暂无真实案例"
}

var suspiciousKeywords = []string{
	"mimikatz", "pwdump", "hashdump", "sekurlsa",
	"kerberos::", "lsass", "Empire", "Metasploit", "Cobalt Strike",
	"bloodhound", "sharphound", "invoke-bloodhound",
}

func IsSuspiciousKeyword(message string) bool {
	messageLower := strings.ToLower(message)
	for _, kw := range suspiciousKeywords {
		if strings.Contains(messageLower, strings.ToLower(kw)) {
			return true
		}
	}
	return false
}
